language: go

go:
  - 1.11.x

install:
  - go get -v -t

script:
  - go build
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - go test -tags integration -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
